version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_DB: transendence
      POSTGRES_USER: nahyulee
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: db
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    restart: always
    networks:
      - mynetwork

  frontend:
    container_name: front
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - back
    restart: always
    networks:
      - mynetwork

  back:
    container_name: back
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: transendence
      POSTGRES_USER: nahyulee
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: db
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: adminpassword
    depends_on:
      - db
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge