version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - mynetwork

  front:
    container_name: front
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - back
    restart: always
    networks:
      - mynetwork

  back:
    container_name: back
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    restart: always
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge