version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    build : ./backend
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always
    networks:
      - transendence

  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/code
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   networks:
  #     - transendence

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /workspaces/ft_transcendence/_data
      o: bind

networks:
  transendence:
    driver: bridge
