version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: transendence
      POSTGRES_USER: nahyulee
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: postgres:5432
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: adminpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - web
    restart: always

  web:
    build: ./backend
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: transendence
      POSTGRES_USER: nahyulee
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: postgres:5432
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: adminpassword
    depends_on:
      - db
    restart: always


volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ../_data
      o: bind