version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_DB: transendence
      POSTGRES_USER: nahyulee
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: postgres:5432
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    restart: always

  frontend:
    container_name: front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - web
    restart: always

  web:
    container_name: web
    build: ./backend
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: transendence
      POSTGRES_USER: nahyulee
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: postgres:5432
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: adminpassword
    depends_on:
      - db
    restart: always
